name: Release Gomni

on:
  push:
    tags:
      - 'v*' # 這裡會針對所有符合 v* 的 tag 進行處理，比如 v0.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # 修改為你專案使用的 Go 版本

      # 3. Build the Go project
      - name: Build project
        run: |
          go mod tidy
          CGO_ENABLED=0 go build -o gomni # 假設你的 main package 在 ./cmd/gomni

      # 4. Create zip archive and tarball of the binary
      - name: Create zip and tarball archive
        run: |
          zip gomni-${{ github.ref_name }}.zip gomni
          tar -czvf gomni-${{ github.ref_name }}.tar.gz gomni

      # 5. Create a release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # v0.1.0
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # 6. Upload Release Assets
      - name: Upload zip file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: gomni-${{ github.ref_name }}.zip
          asset_name: gomni-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      # 7. Upload Release Assets
      - name: Upload tarball file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: gomni-${{ github.ref_name }}.tar.gz
          asset_name: gomni-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      # 8. Upload Release Assets
      - name: Upload install script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: install-completion.sh
          asset_name: install-completion.sh
          asset_content_type: text/x-shellscript
